development:
  fluent_host: '127.0.0.1'
  fluent_port: 24224
  tag:         'outing'

test:
  fluent_host: '127.0.0.1'
  fluent_port: 24224
  tag:         'outing'

production:
  fluent_host: '127.0.0.1'
  fluent_port: 24224
  tag:         'outing'
